name: CI
on:
  push:
    branches: [ main, scratch ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'zulu'
    - name: Build with Maven
      run: ./mvnw install -Dskip.docbkx=true -DskipTests=true -Dmaven.javadoc.skip=true -Djavax.net.ssl.trustStorePassword=changeit -B -V
    - name: List compiled files
      run: |
        echo "Listing JAR files in target directories:"
        find . -name "*.jar" -type f
        echo "Listing all files in target directories:"
        find . -name "target" -type d -exec ls -la {} \;
    - name: Upload compiled artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sqlline-build
        path: |
          **/target/*.jar
          !**/target/*-sources.jar
          !**/target/*-javadoc.jar
        if-no-files-found: warn
